sudo: false
langugage: node_js
services:
  - elasticsearch
node_js:
  - "node"
branches:
  only:
  - master
notifications:
  email: false
before_install: cd OntologyManager
install: npm install
before_script:
  - sleep 10
script: npm test
cache:
  directories:
  - "logs"
