sudo: false
langugage: node_js
node_js:
  - "node"
branches:
  only:
  - master
notifications:
  email: false
before_install: cd OntologyManager
install: npm install
script: npm test
cache:
  directories:
  - "logs"
